// THE THING THAT WAS MISSING: something that constructs a DueInput.
//
// lib/server/dueToReport.ts has defined `DueInput` and `selectDue()` since the
// v1 build opened, and nothing in lib/ or app/ ever built one. The strip's
// three parts were: a state resolver that works, a selector that works, and no
// producer. This is the producer.
//
// ── IT IS A CUT OF 29, NOT OF 50, AND THAT IS NOT A BUG ───────────────────
// Measured 2026-09-22 (relay 35714403198, claude/due-input-census-2026-09-22.md)
// over the committed cut in data/due-strip.json:
//
//   record present             44/50
//   nextPeriodEnd non-null     43/50
//   next.kind === "date"       29/50   <- the only kind carrying medianLagDays
//
// `medianLagDays` exists ONLY on a `{kind:"date"}` estimate. secReportDates
// refuses a date for a filer whose last four lags spread more than
// REGULAR_SPREAD_DAYS, returning `month` or `none` instead, and neither carries
// a lag. selectDue drops any input without one. So 29 is the real ceiling and
// no amount of code here raises it.
//
// ── EIGHT OF THE MISSES ARE STRUCTURAL. DO NOT "FIX" THIS. ────────────────
// ASML, BABA, HSBC, RY, MUFG, NVS, AZN and SHEL are foreign private issuers:
// they announce results on a 6-K, and estimateNextReport counts only events
// whose basis is "8-K item 2.02", so they can never earn a dated estimate and
// can never appear in this strip. That is a property of the ESTIMATOR, which
// the live /stock/[symbol] page also reads -- widening its basis filter to
// admit 6-K would change that page's "next expected" line, which is a
// different decision in a different subsystem and was deliberately not taken
// here. If a later reader finds this list short and reaches for the estimator,
// this comment is the census they did not see.
//
// ── THE COPY ALREADY COVERS IT ────────────────────────────────────────────
// dueStripState's strings say "companies whose fiscal period has ended and
// whose results have not yet been filed", never "all fifty". A strip over 29
// of the cut is a true statement about 29 companies; it is not a claim to be
// exhaustive, and no new copy is needed.
import { readPickersSymbolsIfCached } from "./pickersBuilder";
import { readReportDates, type StoredReportDates } from "./secReportDatesStore";
import { selectDue, type DueInput } from "./dueToReport";
import { resolveDueStrip, type DueStripState } from "./dueStripState";
import cut from "../../data/due-strip.json";

/** The committed cut. Generated by the relay task "due-strip-universe". */
export const DUE_STRIP_CUT: readonly string[] = cut.symbols;
export const DUE_STRIP_CUT_GENERATED_AT: string = cut.generatedAt;

/**
 * Why a cut symbol produced no DueInput. NAMED, not counted.
 *
 * A single "23 skipped" is the shape of verdict this build has spent itself
 * removing: "the cron has not reached this symbol" and "this filer is
 * structurally unable to earn an estimate" are different owners and the same
 * number. Each reason is reported separately with its symbols.
 */
export type DueInputSkip =
  /** Nothing at SEC_REPORT_DATES_PREFIX:<SYMBOL>. The cron has not reached it. */
  | "no-record"
  /** A record, but no cadence to project a period from. */
  | "no-period-end"
  /** A record and a period, but the estimate is "month" or "none" — no lag. */
  | "no-median-lag"
  /**
   * The record's own `pending` says the period's results were ANNOUNCED (an
   * 8-K Item 2.02 newer than anything placed, for a quarter that has ended) and
   * only the SEC feed is behind. "Results have not yet been filed" would be
   * false. This is what takes MU off the strip the day after it reports, rather
   * than weeks later when the 10-K moves the fact set.
   *
   * The early-2.02 guard lives upstream: a TSLA-style delivery 8-K never becomes
   * `pending` (secReportDates.pendingResults), so it cannot take TSLA off.
   */
  | "results-filed";

export type DueInputBuild = {
  inputs: DueInput[];
  skipped: Record<DueInputSkip, string[]>;
};

/**
 * THE UNKNOWN-`annual` DEFAULT, AND WHY IT IS `true`.
 *
 * A record written before StoredReportDates carried `annual` has none, and
 * DueInput.annual is not optional — so this module has to choose. The choice is
 * visible, named and asserted rather than an inline `?? false`.
 *
 * `true` selects the ANNUAL deadline column (60/75/90) over the quarterly one
 * (40/45), which is the SLOWER cap, which keeps a symbol in the strip longer.
 * That follows the rule secReportDates already states for the sibling unknown:
 * "The slowest of the three. An unknown category must not tighten the clamp."
 * Tightening on a guess drops a filer that has done nothing wrong; erring slow
 * shows a statement — "results have not yet been filed" — that is still TRUE,
 * just for longer than the cap intended.
 *
 * This is moot once the sec-facts rotation backfills the field. It exists for
 * the window in between, and the check asserts the direction so a later "tidy
 * up" to `?? false` fails loudly.
 */
export const ANNUAL_WHEN_UNKNOWN = true;

/**
 * One record to one DueInput, or the named reason there isn't one.
 *
 * PURE, and separate from the Redis read above it, because every rule worth
 * asserting is in here and a test that needs a live store to reach them is a
 * test nobody runs.
 */
export function dueInputFrom(
  symbol: string,
  rec: StoredReportDates | null,
): { input: DueInput } | { skip: DueInputSkip } {
  if (!rec || typeof rec !== "object") return { skip: "no-record" };
  if (typeof rec.nextPeriodEnd !== "string" || !rec.nextPeriodEnd) {
    return { skip: "no-period-end" };
  }
  // THE DISCRIMINANT IS THE GATE. `next` is a union and only the "date" arm
  // carries medianLagDays; reading it off the others yields undefined, which
  // selectDue would then drop anyway -- but silently, and counted as though a
  // lag had been offered. Checking the kind is what makes the skip reportable.
  if (rec.pending && typeof rec.pending.periodEnd === "string" && rec.pending.periodEnd >= rec.nextPeriodEnd) {
    return { skip: "results-filed" };
  }
  if (rec.next?.kind !== "date") return { skip: "no-median-lag" };
  const medianLagDays = rec.next.medianLagDays;
  if (!Number.isFinite(medianLagDays)) return { skip: "no-median-lag" };

  return {
    input: {
      symbol,
      periodEnd: rec.nextPeriodEnd,
      medianLagDays,
      // Absent means NOT-YET-BACKFILLED, so null is passed through to
      // deadlineDays, which answers with DEADLINE_FALLBACK. Never coerced to a
      // string: "" would key into FILING_DEADLINE_DAYS as a miss anyway, but it
      // would read as a category we had.
      filerCategory: typeof rec.category === "string" ? rec.category : null,
      annual: typeof rec.annual === "boolean" ? rec.annual : ANNUAL_WHEN_UNKNOWN,
    },
  };
}

/** The cut, in order, against whatever the store holds for it. */
export function buildDueInputs(
  symbols: readonly string[],
  records: ReadonlyMap<string, StoredReportDates | null>,
): DueInputBuild {
  const inputs: DueInput[] = [];
  const skipped: Record<DueInputSkip, string[]> = {
    "no-record": [], "no-period-end": [], "no-median-lag": [], "results-filed": [],
  };
  for (const symbol of symbols) {
    const got = dueInputFrom(symbol, records.get(symbol) ?? null);
    if ("input" in got) inputs.push(got.input);
    else skipped[got.skip].push(symbol);
  }
  return { inputs, skipped };
}

/**
 * How much of the strip's own population can answer "has this filed yet".
 *
 * ── THIS COUNTS THE CUT, AND THE FIRST VERSION COUNTED THE UNIVERSE ───────
 * The instruction for this module was to take the denominator from the
 * 700-symbol analysis universe rather than the 822-entry SEC manifest, because
 * data/due-strip.json was ranked out of the former and a ratio over the latter
 * describes a population the strip is not a cut of. That reasoning is right and
 * it is why the manifest is gone.
 *
 * IT CANNOT BE THE 700 EITHER, AND A COMMITTED GUARD IS WHY. Counting how many
 * of the universe carry report dates needs a per-symbol signal, and the only
 * one that exists is the manifest's `reportDatesAt` stamp. The manifest VALUE
 * is ~417 KB and check-sec-daily-index asserts by name that exactly two job
 * routes may read it — "a new reader, ESPECIALLY A RENDER PATH, still has to be
 * added here deliberately". /earnings-calendar is `force-dynamic`, so this
 * would be that reader on every request. The first draft of this module called
 * readManifest() and that check failed it, correctly.
 *
 * The alternative — one GET per universe symbol — is 700 round trips per
 * render, which is not a render budget either.
 *
 * ── SO THE POPULATION IS THE CUT, WHICH IS ALSO WHAT THE FLOOR IS ABOUT ───
 * dueStripState's floor exists to gate the UNIVERSAL claim ("nothing is
 * outstanding"), and its own rationale is about the cut: "below it the strip
 * cannot see the top-50 cut it renders". The 50 records are already read to
 * build the inputs, so this costs nothing and measures precisely the
 * population the claim is made about — a tighter denominator than either
 * candidate, not a looser one.
 *
 * THE DEPARTURE IS FLAGGED RATHER THAN QUIET. The strip now says "of the fifty
 * I rank, this many can answer" instead of "of the seven hundred". If the
 * literal 700 is wanted, it needs the sec-facts cron to write a small coverage
 * summary key that a render can read in one GET — a new stored value and a
 * second home for a derived number, which is a decision, not an implementation
 * detail.
 *
 * "Can answer" means the record carries at least one observed event. NOT merely
 * that a record exists: sec-facts writes one even for a filer it found no Item
 * 2.02 history for, so existence is the weaker fact and counting it would
 * inflate the ratio in the direction that makes the floor easier to clear.
 */
export function coverageOfCut(
  symbols: readonly string[],
  records: ReadonlyMap<string, StoredReportDates | null>,
): { universeSize: number; withResultsDate: number } {
  let withResultsDate = 0;
  for (const symbol of symbols) {
    const rec = records.get(symbol);
    if (rec && Array.isArray(rec.events) && rec.events.length > 0) withResultsDate++;
  }
  return { universeSize: symbols.length, withResultsDate };
}

/**
 * The strip, end to end, for one day.
 *
 * A FAILED READ IS NOT AN EMPTY ONE, and that is threaded rather than inferred.
 * The analysis universe is read FIRST and for two reasons, neither of them the
 * coverage denominator (see coverageOfCut):
 *
 *   1. It is the one read here that fails DISTINGUISHABLY. readReportDates
 *      returns null for both a missing record and a failed GET, so fifty nulls
 *      cannot tell "the store is unreachable" from "the cron has not run" --
 *      exactly the confusion dueStripState exists to prevent. The universe key
 *      can, so it is the health signal, and its failure is what sets
 *      manifestRead false.
 *   2. It is the population data/due-strip.json was cut from, so a cut that has
 *      drifted out of it is a cut ranking symbols the site no longer covers.
 *      That is reported, not silently tolerated.
 */
export async function getDueStripState(today: string): Promise<DueStripState> {
  const universe = await readPickersSymbolsIfCached();
  if (!Array.isArray(universe) || !universe.length) {
    return resolveDueStrip({
      universeSize: 0, withResultsDate: 0, manifestRead: false, entries: [],
    });
  }

  // ONLY THE CUT IS READ PER SYMBOL. 50 GETs, not 700 -- see coverageOfCut.
  const records = new Map<string, StoredReportDates | null>();
  await Promise.all(
    DUE_STRIP_CUT.map(async (symbol) => {
      records.set(symbol, await readReportDates(symbol));
    }),
  );

  const { inputs } = buildDueInputs(DUE_STRIP_CUT, records);
  const { universeSize, withResultsDate } = coverageOfCut(DUE_STRIP_CUT, records);
  return resolveDueStrip({
    universeSize,
    withResultsDate,
    manifestRead: true,
    entries: selectDue(inputs, today),
  });
}

/** Cut symbols no longer in the analysis universe they were ranked out of. */
export function cutDrift(universe: readonly string[]): string[] {
  const inUniverse = new Set(universe);
  return DUE_STRIP_CUT.filter((s) => !inUniverse.has(s));
}
