import type { MetadataRoute } from "next";
import { getAllPosts } from "@/lib/blog";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://mystockharbor.com";
  const now = new Date();
  const insightPosts = getAllPosts();

  const mainPages = [
    { path: "", changeFrequency: "daily" as const, priority: 1 },
    { path: "/learn", changeFrequency: "weekly" as const, priority: 0.9 },
    { path: "/pickers", changeFrequency: "daily" as const, priority: 0.9 },
    { path: "/platforms", changeFrequency: "weekly" as const, priority: 0.8 },
    { path: "/utilities", changeFrequency: "weekly" as const, priority: 0.7 },
    { path: "/insights", changeFrequency: "daily" as const, priority: 0.85 },
    { path: "/about", changeFrequency: "monthly" as const, priority: 0.5 },
    { path: "/contact", changeFrequency: "monthly" as const, priority: 0.5 },
    { path: "/privacy-policy", changeFrequency: "monthly" as const, priority: 0.4 },
    { path: "/affiliate-disclosure", changeFrequency: "monthly" as const, priority: 0.4 },
    { path: "/risk-disclaimer", changeFrequency: "monthly" as const, priority: 0.4 },
  ];

  const seoGuides = [
    "/how-to-read-stock-charts",
    "/best-stock-indicators-for-beginners",
    "/how-to-identify-stock-trends",
    "/what-is-rsi-indicator",
    "/what-is-macd-indicator",
    "/what-is-vwap-indicator",
    "/stocks-down-from-highs",
    "/oversold-stocks",
    "/breakout-stocks",
    "/buy-the-dip-stocks",
    "/bullish-divergence-stocks",
    "/bearish-divergence-stocks",
    "/overbought-stocks",
    "/stock-market-setups",
    "/trading-setups",
    "/stock-screener-for-breakouts",
    "/stock-screener-for-oversold-stocks",
    "/stocks-down-20-percent",
    "/best-free-stock-screener",
    "/how-to-find-buy-the-dip-stocks",
    "/bullish-divergence-explained",
    "/bearish-divergence-explained",
    "/best-indicators-for-swing-trading",
    "/how-to-scan-stocks",
    "/stocks-ready-to-break-out",
    "/best-charting-platforms",
    "/how-to-analyse-stocks",
    "/stocks-with-high-rsi",
    "/stocks-with-low-rsi",
    "/stocks-with-unusual-volume",
    "/stocks-above-200-day-moving-average",
    "/position-sizing-guide",
    "/stop-loss-strategy",
    "/risk-reward-ratio",
    "/margin-trading-explained",
    "/trading-risk-management",
  ];

  const coreMegaCaps = [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "META",
    "GOOGL",
    "TSLA",
    "BRK.B",
    "AVGO",
    "LLY",
    "JPM",
    "V",
    "MA",
    "COST",
    "UNH",
    "HD",
    "PG",
    "XOM",
    "CVX",
    "MRK",
    "ABBV",
    "PEP",
    "KO",
    "WMT",
    "T",
    "VZ",
    "ORCL",
    "CRM",
    "ADBE",
    "CSCO",
    "INTC",
    "AMD",
    "QCOM",
    "TXN",
    "MCD",
    "SBUX",
    "PYPL",
    "BAC",
    "WFC",
    "TGT",
    "DIS",
  ];

  const retailInterestStocks = [
    "PLTR",
    "SOFI",
    "RIVN",
    "LCID",
    "NIO",
    "HOOD",
    "COIN",
    "DKNG",
    "AFRM",
    "UPST",
    "ROKU",
    "SNAP",
    "PINS",
    "U",
    "SHOP",
    "SQ",
    "RDDT",
    "MSTR",
    "MARA",
    "RIOT",
    "HIMS",
    "CAVA",
    "DUOL",
    "CELH",
    "ARM",
    "SMCI",
    "PATH",
    "CVNA",
    "CHWY",
    "ETSY",
  ];

  const recognizableMidCaps = [
    "F",
    "GM",
    "UBER",
    "LYFT",
    "ABNB",
    "NET",
    "CRWD",
    "PANW",
    "SNOW",
    "ZS",
    "DDOG",
    "OKTA",
    "DOCU",
    "MDB",
    "ZS",
    "TWLO",
    "HUBS",
    "ESTC",
    "TEAM",
    "ZM",
    "BILL",
    "TTD",
    "ROKU",
    "INTU",
    "NOW",
    "ADSK",
    "ANET",
    "MU",
    "KLAC",
    "LRCX",
    "AMAT",
    "ON",
    "MRVL",
    "DELL",
    "HPQ",
    "CSX",
    "UAL",
    "DAL",
    "AAL",
    "CCL",
    "RCL",
    "MAR",
    "HLT",
    "CMG",
    "NKE",
    "LOW",
    "CAT",
    "DE",
    "GE",
    "BA",
    "RTX",
    "PFE",
    "BMY",
    "GILD",
    "AMGN",
    "ISRG",
    "BKNG",
    "MELI",
    "EBAY",
    "WDAY",
    "WDAY",
  ];

  const stocks = Array.from(
    new Set([...coreMegaCaps, ...retailInterestStocks, ...recognizableMidCaps])
  );

  const etfs = [
    "SPY",
    "QQQ",
    "DIA",
    "IWM",
    "VTI",
    "VOO",
    "ARKK",
    "XLF",
    "XLE",
    "XLK",
    "XLP",
    "XLY",
    "XLV",
    "XLRE",
    "XLI",
    "XLC",
    "XLB",
    "XLU",
    "SMH",
    "SOXX",
    "IBIT",
    "HODL",
    "ARKW",
    "VUG",
    "SCHD",
    "DGRO",
    "JEPI",
    "JEPQ",
    "GLD",
    "SLV",
    "TLT",
    "HYG",
  ];

  const mainPageEntries = mainPages.map((page) => ({
    url: `${baseUrl}${page.path}`,
    lastModified: now,
    changeFrequency: page.changeFrequency,
    priority: page.priority,
  }));

  const seoGuideEntries = seoGuides.map((path) => ({
    url: `${baseUrl}${path}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.8,
  }));

  const insightEntries = insightPosts.map((post) => ({
    url: `${baseUrl}/insights/${post.slug}`,
    lastModified: post.date ? new Date(post.date) : now,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  const stockEntries = stocks.map((symbol) => ({
    url: `${baseUrl}/stock/${encodeURIComponent(symbol.toUpperCase())}`,
    lastModified: now,
    changeFrequency: "daily" as const,
    priority: 0.72,
  }));

  const stockNewsEntries = stocks.map((symbol) => ({
    url: `${baseUrl}/stock/${encodeURIComponent(symbol.toUpperCase())}/news`,
    lastModified: now,
    changeFrequency: "daily" as const,
    priority: 0.74,
  }));

  const etfEntries = etfs.map((symbol) => ({
    url: `${baseUrl}/stock/${encodeURIComponent(symbol.toUpperCase())}`,
    lastModified: now,
    changeFrequency: "daily" as const,
    priority: 0.76,
  }));

  const etfNewsEntries = etfs.map((symbol) => ({
    url: `${baseUrl}/stock/${encodeURIComponent(symbol.toUpperCase())}/news`,
    lastModified: now,
    changeFrequency: "daily" as const,
    priority: 0.74,
  }));

  return [
    ...mainPageEntries,
    ...seoGuideEntries,
    ...insightEntries,
    ...stockEntries,
    ...stockNewsEntries,
    ...etfEntries,
    ...etfNewsEntries,
  ];
}
